language: node_js

sudo: false

node_js:
  - "node"

install:
  - npm install -g vsce
  - npm install

script:
  - npm run compile

deploy:
  provider: releases
  file_glob: true
  file: *.vsix
  skip_cleanup: true
  on:
    repo: egormkn/vscode-language-lama
    branch: master
    tags: true
